server.port=5002
spring.application.name=pve-service

# URLs of other microservices (override with env vars in Docker)
data.service.url=${DATA_SERVICE_URL:http://localhost:5003}
battle.service.url=${BATTLE_SERVICE_URL:http://localhost:5001}
